spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=spring_web;encrypt=true;trustServerCertificate=true
spring.datasource.username=lab_user
spring.datasource.password=Lab_pass1
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC